### ISSUE TITLE
如何增加和减少设备?

### ISSUE THREAD

**Issue by befantasy** [FlashSoft/ha-airx#2]
默认提供两个airx设备, 不值如何修改可以最简便的增加和减少设备?

**Comment by flashsoft** [comment]
范例里只是示范两个airx设备而已，你可以随便删除

**Comment by befantasy** [comment]
谢谢，已经解决了。但是最近以来以一直遇到另一个问题：无法更新设备状态和城市PM状态。一直提示超时。重启homeassistant可以解决，但没隔多久又会一直挂死。

**Comment by flashsoft** [comment]
建议直接使用NR来玩，不太推荐HA
